#!/bin/sh
# NeoRadio post-install cleanup: remove temporary installer/update files from /tmp.
rm -f /tmp/neoradio_update.ipk
rm -f /tmp/enigma2-plugin-extensions-neoradio*.ipk
rm -f /tmp/neoradio*.ipk
rm -f /tmp/NeoRadio*.ipk
rm -rf /tmp/neoradio /tmp/NeoRadio /tmp/neoradio_tmp /tmp/neoradio_install
exit 0
